import {supabaseServer} from '@/lib/supabase/server';
import {localeOf} from '@/lib/i18n';
import {APP_COMMUNICATIONS,whatsappUrl} from '@/lib/communications';

function money(value:number|null,currency:string){if(value==null)return null;try{return new Intl.NumberFormat('es-US',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value));}catch{return `${Number(value).toFixed(2)} ${currency}`}}
function eta(min:number|null,max:number|null){if(min==null&&max==null)return null;if(min!=null&&max!=null)return `${min}–${max} min`;return min!=null?`Desde ${min} min`:`Hasta ${max} min`;}

export default async function LocalServices({params}:{params:Promise<{locale:string}>}){
  const {locale:raw}=await params;const locale=localeOf(raw);const es=locale==='es';
  const supabase=await supabaseServer();
  const [{data:services,error:serviceError},{data:providers,error:providerError}]=await Promise.all([
    supabase.from('delivery_provider_public_services').select('public_provider_id,service_code,display_name_es,display_name_en,category,fee_currency,starting_fee,minimum_fee,maximum_fee,eta_min_minutes,eta_max_minutes,conditions,updated_at').order('category').order('starting_fee',{ascending:true,nullsFirst:false}),
    supabase.from('delivery_provider_public_directory').select('public_provider_id,display_name,city,region,country_code,service_area,service_zones,verified,accepting_jobs').eq('verified',true)
  ]);
  const providerMap=new Map((providers??[]).map((p:any)=>[p.public_provider_id,p]));
  const rows=(services??[]).map((s:any)=>({...s,provider:providerMap.get(s.public_provider_id)})).filter((s:any)=>s.provider&&s.provider.accepting_jobs);
  const unavailable=Boolean(serviceError||providerError);
  const channels=APP_COMMUNICATIONS;
  const categories=['TOPUP','COMMERCE','ERRAND','DELIVERY','OTHER'];
  const cat=(value:string)=>es?({TOPUP:'Recargas',COMMERCE:'Compras + entrega',ERRAND:'Mandados y mensajería',DELIVERY:'Entrega',OTHER:'Otros servicios'} as any)[value]:({TOPUP:'Top-ups',COMMERCE:'Purchase + delivery',ERRAND:'Errands & messenger',DELIVERY:'Delivery',OTHER:'Other services'} as any)[value];

  return <main className="shell premiumAppShell">
    <nav className="nav premiumNav"><a href={`/${locale}`} className="brandwrap"><div className="brand">mycubacash</div><small>{es?'Servicios dentro de Cuba':'Services in Cuba'}</small></a><div className="navlinks"><a href={`/${locale}/delivery-providers`}>{es?'Delivery':'Delivery'}</a><a href={`/${locale}/marketplace`}>{es?'Marketplace':'Marketplace'}</a><a href={`/${locale}/delivery-providers/services`}>{es?'Ofrecer servicios':'Offer services'}</a></div></nav>
    <section className="cinematicHero" style={{minHeight:'72vh'}}><div className="cinematicHeroOverlay"/><div className="cinematicHeroContent"><span className="eyebrow">{es?'SERVICIOS LOCALES · CUBA':'LOCAL SERVICES · CUBA'}</span><h1>{es?'Una necesidad. Varias opciones. Tú eliges.':'One need. Multiple options. You choose.'}</h1><p className="heroLead">{es?'Compara proveedores verificados para recargas Cubacel, Nauta, compras, alimentos, medicinas, mensajería, diligencias y delivery. Precio, ETA y cobertura antes de elegir.':'Compare verified providers for Cubacel and Nauta top-ups, purchases, food, medicine, messenger, errands and delivery. See price, ETA and coverage before choosing.'}</p><div className="actions"><a className="cta premiumCta" href={whatsappUrl(channels.whatsappPrimary.e164,es?'Necesito ayuda para encontrar un servicio local dentro de Cuba.':'I need help finding a local service in Cuba.')}>{es?'Pedir ayuda a Sofia':'Ask Sofia'}</a><a className="glassCta" href={`/${locale}/delivery-providers/services`}>{es?'Soy proveedor':'I am a provider'}</a></div></div></section>

    <section className="section">
      <div className="sectionHead"><div><span className="eyebrow">{es?'COMPARACIÓN TRANSPARENTE':'TRANSPARENT COMPARISON'}</span><h2>{es?'Servicios publicados por proveedores verificados':'Services posted by verified providers'}</h2></div><p>{es?'El cargo del proveedor se muestra separado del valor de una recarga, compra u otro producto. La disponibilidad y los tiempos son estimados hasta que el proveedor confirme el trabajo.':'Provider fees are shown separately from the value of a top-up, purchase or other product. Availability and timing are estimates until the provider confirms the job.'}</p></div>
      {unavailable?<div className="feature premiumCard"><h3>{es?'Servicios temporalmente no disponibles':'Services temporarily unavailable'}</h3><p>{es?'Sofia puede ayudarte por WhatsApp Business.':'Sofia can help on WhatsApp Business.'}</p></div>:!rows.length?<div className="feature premiumCard"><h3>{es?'La red está abriendo':'The network is opening'}</h3><p>{es?'Todavía no hay servicios locales aprobados y públicos. No mostramos proveedores inventados.':'There are no approved public local services yet. We do not show fabricated providers.'}</p></div>:categories.map(category=>{const items=rows.filter((r:any)=>r.category===category);if(!items.length)return null;return <section key={category} style={{marginBottom:44}}><div className="sectionHead"><div><span className="eyebrow">{category}</span><h2>{cat(category)}</h2></div></div><div className="featureGrid">{items.map((s:any)=>{const p=s.provider;const start=money(s.starting_fee,s.fee_currency||'USD');const min=money(s.minimum_fee,s.fee_currency||'USD');const max=money(s.maximum_fee,s.fee_currency||'USD');const etaText=eta(s.eta_min_minutes,s.eta_max_minutes);const serviceName=es?s.display_name_es:s.display_name_en;return <article className="feature premiumCard" key={`${s.public_provider_id}-${s.service_code}`}><div className="deliveryChoiceTop"><div><span className="eyebrow">{s.service_code}</span><h3>{serviceName}</h3></div><span className="previewTag">{es?'VERIFICADO':'VERIFIED'}</span></div><p><strong>{p.display_name}</strong></p><p>{[p.city,p.region,p.country_code].filter(Boolean).join(' · ')}</p>{start&&<p><strong>{es?'Servicio desde:':'Service from:'}</strong> {start}</p>}{(min||max)&&<p><strong>{es?'Rango:':'Range:'}</strong> {min?`${es?'mín.':'min'} ${min}`:''}{min&&max?' · ':''}{max?`${es?'máx.':'max'} ${max}`:''}</p>}{etaText&&<p><strong>ETA:</strong> {etaText}</p>}{s.conditions&&<p>{s.conditions}</p>}<div className="actions"><a className="ghost" href={whatsappUrl(channels.whatsappPrimary.e164,es?`Quiero solicitar ${serviceName} con ${p.display_name}. Referencia del proveedor: ${s.public_provider_id}.`:`I want to request ${serviceName} with ${p.display_name}. Provider reference: ${s.public_provider_id}.`)}>{es?'Solicitar este servicio':'Request this service'}</a></div></article>})}</div></section>})}
    </section>
    <section className="policyBlock"><div><span className="eyebrow">{es?'CONFIANZA + LÍMITES':'TRUST + BOUNDARIES'}</span><h2>{es?'Servicios locales verificados, sin ocultar actividades financieras dentro de una categoría genérica.':'Verified local services without hiding financial activity inside a generic category.'}</h2></div><p>{es?'mycubacash puede listar recargas, compras, entrega y diligencias aprobadas. Transmisión de dinero, cambio de moneda, custodia o liquidación requieren controles y proveedores autorizados separados.':'mycubacash may list approved top-ups, purchases, delivery and errands. Money transmission, currency exchange, custody or settlement require separate controls and appropriately authorized providers.'}</p></section>
  </main>;
}
