import {localeOf} from '@/lib/i18n';
import {stripeConfigured} from '@/lib/stripe';
import {supabaseServer} from '@/lib/supabase/server';
import CheckoutButton from '../../business-pricing/CheckoutButton';

export default async function SponsorCatalogItem({params}:{params:Promise<{locale:string}>}){
  const {locale:raw}=await params;const locale=localeOf(raw);const es=locale==='es';
  const supabase=await supabaseServer();const {data:{user}}=await supabase.auth.getUser();
  if(!user)return <main className="shell premiumAppShell"><section className="section"><h1>{es?'Acceso requerido':'Sign in required'}</h1><a className="cta premiumCta" href={`/${locale}/auth?next=/${locale}/catalog/sponsor`}>{es?'Entrar para elegir un producto':'Sign in to choose a product'}</a></section></main>;
  const {data:items}=await supabase.from('provider_catalog_items').select('id,title,category,image_url,sponsored_until').eq('provider_user_id',user.id).eq('review_status','APPROVED').eq('available',true).order('updated_at',{ascending:false});
  const checkoutReady=stripeConfigured();
  return <main className="shell premiumAppShell"><nav className="nav premiumNav"><a href={`/${locale}/business-pricing`} className="brandwrap"><div className="brand">MY CUBA CASH</div><small>{es?'Producto patrocinado':'Sponsored product'}</small></a><div className="navlinks"><a href={`/${locale}/catalog/manage`}>{es?'Mi catálogo':'My catalog'}</a><a href={`/${locale}/business-pricing`}>{es?'Planes':'Plans'}</a></div></nav><section className="section"><div className="sectionHead"><div><span className="eyebrow">$25 · 7 {es?'DÍAS':'DAYS'}</span><h1>{es?'Elige un artículo aprobado para promocionar.':'Choose an approved item to promote.'}</h1></div><p>{es?'La promoción mejora visibilidad temporalmente; no cambia verificación, reputación ni posición orgánica permanente.':'Promotion temporarily improves visibility; it does not change verification, reputation or permanent organic standing.'}</p></div>{!items?.length?<div className="feature premiumCard"><h3>{es?'No hay artículos aprobados disponibles.':'No approved items are available.'}</h3><p>{es?'Crea un artículo y espera su aprobación antes de comprar promoción.':'Create an item and wait for approval before buying promotion.'}</p><a className="ghost" href={`/${locale}/catalog/manage`}>{es?'Gestionar catálogo':'Manage catalog'}</a></div>:<div className="featureGrid">{items.map(item=>{const active=Boolean(item.sponsored_until&&new Date(item.sponsored_until).getTime()>Date.now());return <article className="feature premiumCard" key={item.id}>{item.image_url&&<img src={item.image_url} alt={item.title} style={{width:'100%',height:180,objectFit:'cover',borderRadius:12}}/>}<span className="eyebrow">{item.category}</span><h3>{item.title}</h3>{active?<p><strong>{es?'Patrocinado hasta':'Sponsored until'}:</strong> {new Date(item.sponsored_until).toLocaleDateString(es?'es-US':'en-US')}</p>:<CheckoutButton offerCode="SPONSORED_7D" targetId={item.id} locale={locale} label={es?'Patrocinar 7 días · $25':'Sponsor 7 days · $25'} disabled={!checkoutReady}/>}</article>})}</div>}</section></main>;
}
