import {supabaseServer} from '@/lib/supabase/server';
export const dynamic='force-dynamic';
const ISO2=/^[A-Z]{2}$/;
function json(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
export async function GET(){const s=await supabaseServer();const {data:{user}}=await s.auth.getUser();if(!user)return json({error:'UNAUTHORIZED'},401);const [{data:membership},{data:provider},{data:businesses}]=await Promise.all([s.from('provider_memberships').select('*').eq('user_id',user.id).maybeSingle(),s.from('delivery_provider_profiles').select('user_id,business_id,public_provider_id,display_name,country_code,city,region,profile_status').eq('user_id',user.id).maybeSingle(),s.from('businesses').select('id,legal_name,trade_name,country_code,business_type,registration_number,kyb_status,sanctions_status').eq('owner_user_id',user.id)]);return json({membership,provider,businesses:businesses??[]})}
export async function POST(req:Request){const s=await supabaseServer();const {data:{user}}=await s.auth.getUser();if(!user)return json({error:'UNAUTHORIZED'},401);let b:any;try{b=await req.json()}catch{return json({error:'INVALID_JSON'},400)};if(b.acceptedProviderAgreement!==true)return json({error:'PROVIDER_AGREEMENT_REQUIRED'},400);const country=String(b.countryCode??'').trim().toUpperCase();const legal=String(b.legalName??'').trim();const display=String(b.displayName??b.tradeName??legal).trim();const type=String(b.businessType??'PRIVATE_BUSINESS').trim();if(!ISO2.test(country)||legal.length<2||display.length<2)return json({error:'IDENTITY_AND_COUNTRY_REQUIRED'},400);let businessId=String(b.businessId??'');if(businessId){const {data:owned}=await s.from('businesses').select('id').eq('id',businessId).eq('owner_user_id',user.id).maybeSingle();if(!owned)return json({error:'BUSINESS_NOT_OWNED'},403)}else{const {data:biz,error}=await s.from('businesses').insert({legal_name:legal,trade_name:b.tradeName?String(b.tradeName).trim():null,country_code:country,business_type:type,registration_number:b.registrationNumber?String(b.registrationNumber).trim():null,owner_user_id:user.id}).select('id').single();if(error)return json({error:'BUSINESS_CREATE_FAILED'},400);businessId=biz.id}
const {error:profileError}=await s.from('delivery_provider_profiles').upsert({user_id:user.id,provider_kind:'BUSINESS',business_id:businessId,display_name:display,phone:b.phone?String(b.phone).trim():null,city:b.city?String(b.city).trim():null,region:b.region?String(b.region).trim():null,country_code:country,service_area:b.serviceArea?String(b.serviceArea).trim():null,profile_status:'SUBMITTED',updated_at:new Date().toISOString()},{onConflict:'user_id'});if(profileError)return json({error:'PROVIDER_PROFILE_FAILED'},400);
const {data:cap}=await s.from('user_capabilities').select('user_id').eq('user_id',user.id).eq('capability','BUSINESS_DELIVERY_PROVIDER').maybeSingle();if(!cap){await s.from('user_capabilities').insert({user_id:user.id,capability:'BUSINESS_DELIVERY_PROVIDER'})}
const {data:membership,error:membershipError}=await s.from('provider_memberships').insert({user_id:user.id,business_id:businessId,plan_code:'PROVIDER_STANDARD',provider_agreement_accepted_at:new Date().toISOString()}).select('*').single();if(membershipError&&membershipError.code!=='23505')return json({error:'MEMBERSHIP_REQUEST_FAILED'},400);return json({membership:membership??null,status:'PENDING_VERIFICATION',message:'Provider membership requested. Public visibility remains disabled until membership and identity are verified.'},201)}
