export const locales = ['es','en','fr','pt','ar'] as const;
export type Locale = typeof locales[number];

export const copy: Record<Locale, Record<string,string>> = {
  es: {brand:'mycubacash.com',tag:'La plataforma operativa de la economía privada',market:'Marketplace',rfq:'RFQs',trade:'Comercio',compliance:'Cumplimiento',ledger:'Ledger',businesses:'Empresas',hero:'Conecta, compra, vende y opera con controles empresariales de nivel institucional.',cta:'Abrir panel',status:'Estado del sistema',corridors:'Corredores',private:'Sector privado',global:'Comercio global',safe:'Controles fail-closed',notice:'mycubacash.com no es un banco. Los pagos y operaciones reguladas requieren proveedores, autorizaciones y revisión aplicables.'},
  en: {brand:'mycubacash.com',tag:'The operating platform for the private-sector economy',market:'Marketplace',rfq:'RFQs',trade:'Trade',compliance:'Compliance',ledger:'Ledger',businesses:'Businesses',hero:'Connect, buy, sell and operate with institution-grade business controls.',cta:'Open dashboard',status:'System status',corridors:'Corridors',private:'Private sector',global:'Global trade',safe:'Fail-closed controls',notice:'mycubacash.com is not a bank. Payments and regulated activity require applicable providers, authorizations and review.'},
  fr: {brand:'mycubacash.com',tag:"La plateforme opérationnelle de l’économie privée",market:'Marché',rfq:'RFQ',trade:'Commerce',compliance:'Conformité',ledger:'Registre',businesses:'Entreprises',hero:'Connecter, acheter, vendre et opérer avec des contrôles de niveau institutionnel.',cta:'Ouvrir le tableau de bord',status:'État du système',corridors:'Corridors',private:'Secteur privé',global:'Commerce mondial',safe:'Contrôles fail-closed',notice:"mycubacash.com n’est pas une banque. Les paiements et activités réglementées exigent les prestataires, autorisations et contrôles applicables."},
  pt: {brand:'mycubacash.com',tag:'A plataforma operacional da economia privada',market:'Marketplace',rfq:'RFQs',trade:'Comércio',compliance:'Conformidade',ledger:'Livro-razão',businesses:'Empresas',hero:'Conecte, compre, venda e opere com controles empresariais de nível institucional.',cta:'Abrir painel',status:'Status do sistema',corridors:'Corredores',private:'Setor privado',global:'Comércio global',safe:'Controles fail-closed',notice:'mycubacash.com não é um banco. Pagamentos e atividades reguladas exigem provedores, autorizações e revisão aplicáveis.'},
  ar: {brand:'mycubacash.com',tag:'منصة تشغيل للاقتصاد الخاص',market:'السوق',rfq:'طلبات عروض الأسعار',trade:'التجارة',compliance:'الامتثال',ledger:'السجل',businesses:'الشركات',hero:'تواصل واشترِ وبِع وشغّل أعمالك بضوابط مؤسسية.',cta:'فتح لوحة التحكم',status:'حالة النظام',corridors:'الممرات',private:'القطاع الخاص',global:'التجارة العالمية',safe:'ضوابط إيقاف آمنة',notice:'mycubacash.com ليس بنكاً. تتطلب المدفوعات والأنشطة المنظمة مزودين وتراخيص ومراجعات مناسبة.'}
};

export function localeOf(value?: string): Locale { return locales.includes(value as Locale) ? value as Locale : 'es'; }
