export const locales = ['es','en','fr','pt','ar'] as const;
export type Locale = typeof locales[number];

type Copy = {
  brand:string; tag:string; hero:string; subhero:string; cta:string; secondary:string;
  market:string; rfq:string; trade:string; compliance:string; ledger:string; businesses:string;
  status:string; corridors:string; private:string; global:string; safe:string;
  networkTitle:string; networkBody:string; commerceTitle:string; commerceBody:string;
  tradeTitle:string; tradeBody:string; controlsTitle:string; controlsBody:string;
  policyNotice:string; dashboard:string; evidence:string; verified:string; orchestration:string;
};

export const copy: Record<Locale, Copy> = {
  es: {brand:'MY CUBA CASH',tag:'La plataforma operativa de la economía privada',hero:'La infraestructura digital para operar, comprar, vender y crecer en el sector privado.',subhero:'Unifica identidad empresarial, marketplace, RFQs, comercio, operaciones y controles en una sola plataforma multilingüe.',cta:'Entrar al Command Center',secondary:'Explorar la plataforma',market:'Marketplace',rfq:'RFQs',trade:'Comercio',compliance:'Controles',ledger:'Registro',businesses:'Empresas',status:'Estado',corridors:'Corredores',private:'Sector privado',global:'Comercio global',safe:'Policy Engine',networkTitle:'Red privada empresarial',networkBody:'Perfiles de empresas, emprendedores, cooperativas, compradores, proveedores y prestadores con identidad y evidencia empresarial.',commerceTitle:'Marketplace + Procurement',commerceBody:'Demanda, ofertas, RFQs, sourcing y comparación de oportunidades sin inventar disponibilidad ni contrapartes.',tradeTitle:'Importación, exportación y comercio interno',tradeBody:'Flujos CU-CU, CU-WORLD, WORLD-CU, CU-US y WORLD-WORLD con documentación, logística y trazabilidad.',controlsTitle:'Policy & Compliance Orchestration',controlsBody:'KYC/KYB, beneficiario final, sanciones, señales de fraude, evidencia y decisiones fail-closed.',policyNotice:'MY CUBA CASH opera como capa de política y orquestación para el sector privado. Los datos de sanciones, obligaciones legales por jurisdicción y decisiones de presentación deben apoyarse en fuentes oficiales vigentes y, cuando corresponda, personal de cumplimiento o legal autorizado.',dashboard:'Command Center',evidence:'Evidencia',verified:'Fuente verificada',orchestration:'Orquestación'},
  en: {brand:'MY CUBA CASH',tag:'The operating platform for the private-sector economy',hero:'Digital infrastructure to operate, buy, sell and grow across the private sector.',subhero:'Unify business identity, marketplace, RFQs, trade, operations and controls in one multilingual platform.',cta:'Enter Command Center',secondary:'Explore platform',market:'Marketplace',rfq:'RFQs',trade:'Trade',compliance:'Controls',ledger:'Registry',businesses:'Businesses',status:'Status',corridors:'Corridors',private:'Private sector',global:'Global trade',safe:'Policy Engine',networkTitle:'Private business network',networkBody:'Profiles for businesses, entrepreneurs, cooperatives, buyers, suppliers and service providers with business identity and evidence.',commerceTitle:'Marketplace + Procurement',commerceBody:'Demand, offers, RFQs, sourcing and opportunity comparison without fabricating availability or counterparties.',tradeTitle:'Imports, exports and domestic commerce',tradeBody:'CU-CU, CU-WORLD, WORLD-CU, CU-US and WORLD-WORLD workflows with documentation, logistics and traceability.',controlsTitle:'Policy & Compliance Orchestration',controlsBody:'KYC/KYB, beneficial ownership, sanctions, fraud signals, evidence and fail-closed decisioning.',policyNotice:'MY CUBA CASH operates as the policy and orchestration layer for the private sector. Sanctions data, jurisdiction-specific legal obligations and filing decisions must remain tied to current authoritative sources and, where required, appropriately authorized compliance or legal personnel.',dashboard:'Command Center',evidence:'Evidence',verified:'Verified source',orchestration:'Orchestration'},
  fr: {brand:'MY CUBA CASH',tag:"La plateforme opérationnelle de l’économie privée",hero:"L’infrastructure numérique pour exploiter, acheter, vendre et développer l’économie privée.",subhero:"Identité d’entreprise, marché, RFQ, commerce, opérations et contrôles réunis dans une plateforme multilingue.",cta:'Ouvrir le Command Center',secondary:'Explorer la plateforme',market:'Marché',rfq:'RFQ',trade:'Commerce',compliance:'Contrôles',ledger:'Registre',businesses:'Entreprises',status:'État',corridors:'Corridors',private:'Secteur privé',global:'Commerce mondial',safe:'Policy Engine',networkTitle:'Réseau privé d’entreprises',networkBody:'Profils d’entreprises, entrepreneurs, coopératives, acheteurs, fournisseurs et prestataires avec identité et preuves.',commerceTitle:'Marketplace + Achats',commerceBody:'Demandes, offres, RFQ, sourcing et comparaison sans inventer la disponibilité ni les contreparties.',tradeTitle:'Import, export et commerce intérieur',tradeBody:'Flux CU-CU, CU-WORLD, WORLD-CU, CU-US et WORLD-WORLD avec documents, logistique et traçabilité.',controlsTitle:'Orchestration politique et conformité',controlsBody:'KYC/KYB, bénéficiaires effectifs, sanctions, signaux de fraude, preuves et décisions fail-closed.',policyNotice:'MY CUBA CASH sert de couche de politique et d’orchestration du secteur privé. Les données de sanctions, obligations juridiques par juridiction et décisions de déclaration doivent rester liées aux sources officielles actuelles et, si nécessaire, au personnel conformité ou juridique autorisé.',dashboard:'Command Center',evidence:'Preuves',verified:'Source vérifiée',orchestration:'Orchestration'},
  pt: {brand:'MY CUBA CASH',tag:'A plataforma operacional da economia privada',hero:'A infraestrutura digital para operar, comprar, vender e crescer no setor privado.',subhero:'Unifique identidade empresarial, marketplace, RFQs, comércio, operações e controles em uma plataforma multilíngue.',cta:'Entrar no Command Center',secondary:'Explorar a plataforma',market:'Marketplace',rfq:'RFQs',trade:'Comércio',compliance:'Controles',ledger:'Registro',businesses:'Empresas',status:'Status',corridors:'Corredores',private:'Setor privado',global:'Comércio global',safe:'Policy Engine',networkTitle:'Rede empresarial privada',networkBody:'Perfis de empresas, empreendedores, cooperativas, compradores, fornecedores e prestadores com identidade e evidências.',commerceTitle:'Marketplace + Compras',commerceBody:'Demanda, ofertas, RFQs, sourcing e comparação sem inventar disponibilidade ou contrapartes.',tradeTitle:'Importação, exportação e comércio interno',tradeBody:'Fluxos CU-CU, CU-WORLD, WORLD-CU, CU-US e WORLD-WORLD com documentos, logística e rastreabilidade.',controlsTitle:'Orquestração de política e conformidade',controlsBody:'KYC/KYB, beneficiário final, sanções, sinais de fraude, evidências e decisões fail-closed.',policyNotice:'MY CUBA CASH opera como camada de política e orquestração do setor privado. Dados de sanções, obrigações jurídicas específicas por jurisdição e decisões de apresentação devem permanecer vinculados a fontes oficiais atuais e, quando necessário, a pessoal autorizado de compliance ou jurídico.',dashboard:'Command Center',evidence:'Evidências',verified:'Fonte verificada',orchestration:'Orquestração'},
  ar: {brand:'MY CUBA CASH',tag:'منصة تشغيل للاقتصاد الخاص',hero:'بنية رقمية للتشغيل والشراء والبيع والنمو في القطاع الخاص.',subhero:'توحيد هوية الأعمال والسوق وطلبات الأسعار والتجارة والعمليات والضوابط في منصة متعددة اللغات.',cta:'دخول مركز القيادة',secondary:'استكشاف المنصة',market:'السوق',rfq:'طلبات الأسعار',trade:'التجارة',compliance:'الضوابط',ledger:'السجل',businesses:'الشركات',status:'الحالة',corridors:'الممرات',private:'القطاع الخاص',global:'التجارة العالمية',safe:'محرك السياسات',networkTitle:'شبكة الأعمال الخاصة',networkBody:'ملفات للشركات ورواد الأعمال والتعاونيات والمشترين والموردين ومقدمي الخدمات مع هوية وأدلة أعمال.',commerceTitle:'السوق + المشتريات',commerceBody:'الطلب والعروض وطلبات الأسعار والتوريد والمقارنة دون اختلاق توافر أو أطراف مقابلة.',tradeTitle:'الاستيراد والتصدير والتجارة المحلية',tradeBody:'تدفقات CU-CU وCU-WORLD وWORLD-CU وCU-US وWORLD-WORLD مع الوثائق والخدمات اللوجستية والتتبع.',controlsTitle:'تنسيق السياسات والامتثال',controlsBody:'KYC/KYB والملكية المستفيدة والعقوبات وإشارات الاحتيال والأدلة والقرارات الآمنة.',policyNotice:'تعمل MY CUBA CASH كطبقة سياسات وتنسيق للقطاع الخاص. يجب أن تظل بيانات العقوبات والالتزامات القانونية حسب الولاية وقرارات الإيداع مرتبطة بمصادر رسمية حديثة وبالموظفين المخولين في الامتثال أو الشؤون القانونية عند الحاجة.',dashboard:'مركز القيادة',evidence:'الأدلة',verified:'مصدر موثوق',orchestration:'التنسيق'}
};

export function localeOf(value?: string): Locale { return locales.includes(value as Locale) ? value as Locale : 'es'; }
