import {localeOf} from '@/lib/i18n';

export default async function AboutPage({params}:{params:Promise<{locale:string}>}){
  const {locale:raw}=await params;
  const locale=localeOf(raw);
  const es=locale==='es';
  return <main className="shell premiumAppShell" dir={locale==='ar'?'rtl':'ltr'}>
    <nav className="nav premiumNav"><a href={`/${locale}`} className="brandwrap"><div className="brand">MY CUBA CASH</div><small>{es?'Quiénes somos':'About us'}</small></a><div className="navlinks"><a href={`/${locale}/how-it-works`}>{es?'Cómo funciona':'How it works'}</a><a href={`/${locale}/fees`}>{es?'Tarifas':'Fees'}</a><a href={`/${locale}/contact`}>{es?'Contacto':'Contact'}</a></div></nav>
    <section className="hero"><div className="heroCopy"><div className="eyebrow">{es?'QUIÉNES SOMOS':'WHO WE ARE'}</div><h1>MY CUBA CASH</h1><p className="heroSub">www.mycubacash.com · {es?'Operado por SAHJONY LLC · Beta v0.9':'Operated by SAHJONY LLC · Beta v0.9'}</p><p className="heroLead">{es?'Una plataforma tecnológica en beta (v0.9) operada por SAHJONY LLC para enviar apoyo familiar, comprar productos y contratar servicios de MIPYMEs, emprendedores y actores privados verificados en Cuba, con costos, opciones y seguimiento visibles.':'A technology platform in beta (v0.9) operated by SAHJONY LLC for family support, products and services from verified Cuban private businesses, entrepreneurs and providers, with visible costs, options and tracking.'}</p></div></section>
    <section className="section"><div className="sectionHead"><div><span className="eyebrow">{es?'LA OPERADORA':'THE OPERATOR'}</span><h2>{es?'Quién está detrás de la plataforma.':'Who is behind the platform.'}</h2></div></div>
    <div className="featureGrid">
      <article className="feature premiumCard"><span className="eyebrow">{es?'OPERADOR':'OPERATOR'}</span><h3>SAHJONY LLC</h3><p>{es?'MY CUBA CASH es una plataforma tecnológica operada por SAHJONY LLC.':'MY CUBA CASH is a technology platform operated by SAHJONY LLC.'}</p></article>
      <article className="feature premiumCard"><span className="eyebrow">{es?'PROPIETARIO':'OWNER'}</span><h3>Juan Gonzalez</h3><p>{es?'Chairman and owner of SAHJONY LLC. Responsable final de la operación de la plataforma.':'Chairman and owner of SAHJONY LLC. Ultimately responsible for the platform operation.'}</p></article>
      <article className="feature premiumCard"><span className="eyebrow">{es?'FRENTE DE CONCIERGE':'CONCIERGE FRONT'}</span><h3>Sofia Smith</h3><p>{es?'Executive Manager of SAHJONY LLC. Coordinación de solicitudes, explicación de opciones y próximos pasos.':'Executive Manager of SAHJONY LLC. Request coordination, option explanations and next steps.'}</p></article>
      <article className="feature premiumCard"><span className="eyebrow">{es?'ESTADO ACTUAL':'CURRENT STATUS'}</span><h3>Beta v0.9</h3><p>{es?'La plataforma está en beta: funciona con proveedores reales verificados y muestra estado de red, límites y costos visibles. La red pública está en pre-lanzamiento mientras no existan proveedores verificados publicados.':'The platform is in beta: it works with real verified providers and shows visible network status, limits and costs. The public network is in pre-launch while no verified providers are listed.'}</p></article>
    </div></section>
    <section className="section"><div className="sectionHead"><div><span className="eyebrow">{es?'NUESTRA MISIÓN':'OUR MISSION'}</span><h2>{es?'Transparencia primero. Proveedores reales, costos reales.':'Transparency first. Real providers, real costs.'}</h2></div><p>{es?'MY CUBA CASH existe para que la diáspora apoye a su familia y al sector privado cubano sin cifras inventadas ni promesas que no podemos respaldar. Mostramos tarifa, estado real de la red, opciones publicadas y seguimiento — y decimos claramente lo que todavía no está disponible.':'MY CUBA CASH exists so the diaspora can support family and Cuba’s private sector without invented figures or promises we cannot back. We show fees, real network status, published options and tracking — and we say clearly what is not yet available.'}</p></div>
    <div className="featureGrid">
      <article className="feature premiumCard"><h3>{es?'Lo que hacemos':'What we do'}</h3><p>{es?'Conectamos a clientes con una red privada verificada para enviar apoyo familiar, comprar productos y contratar servicios. Mostramos tarifa, estado real de la red, opciones publicadas y seguimiento.':'We connect customers with a verified private network for family support, products and services. We show fees, real network status, published options and tracking.'}</p></article>
      <article className="feature premiumCard"><h3>{es?'Lo que no prometemos':'What we do not promise'}</h3><p>{es?'No garantizamos una entrega, tipo de cambio, proveedor o importe recibido antes de que estén confirmados.':'We do not guarantee delivery, an exchange rate, a provider or an amount received before confirmation.'}</p></article>
      <article className="feature premiumCard"><span className="eyebrow">{es?'CUSTODIA CERO':'ZERO CUSTODY'}</span><h3>{es?'Nunca custodian tu dinero.':'We never hold your money.'}</h3><p>{es?'MY CUBA CASH nunca toma custodia del principal. El cliente paga directamente al banco, proveedor o prestador del servicio. Crear una solicitud no mueve fondos.':'MY CUBA CASH never takes custody of the principal. The customer pays the bank, provider or service provider directly. Creating a request does not move funds.'}</p></article>
      <article className="feature premiumCard"><span className="eyebrow">{es?'ESTADO REGULATORIO':'REGULATORY STATUS'}</span><h3>{es?'Coordinación y orientación.':'Coordination and guidance.'}</h3><p>{es?'MY CUBA CASH no posee actualmente una licencia de transmisor de dinero y opera como orientación de navegación y coordinación únicamente, no como transmisor de dinero. Cuando una actividad requiera transmisión, custodia, cambio de moneda o liquidación regulada, debe ejecutarse mediante el proveedor debidamente autorizado y el flujo aplicable antes de mover fondos.':'MY CUBA CASH does not currently hold a money-transmitter license and operates as navigation and coordination guidance only, not as a money transmitter. When an activity requires regulated money transmission, custody, currency exchange or settlement, it must be performed through the appropriately authorized provider and applicable flow before funds move.'}</p></article>
    </div></section>
    <section className="policyBlock premiumPolicy"><div><span className="eyebrow">{es?'ALCANCE':'SCOPE'}</span><h2>{es?'Tecnología y coordinación con controles separados.':'Technology and coordination with separate controls.'}</h2></div><p>{es?'MY CUBA CASH no se presenta como banco. Cualquier movimiento de fondos debe ocurrir mediante el flujo autorizado aplicable y después de satisfacer identidad, sanciones, fraude, pago, corredor y controles de proveedor.':'MY CUBA CASH does not present itself as a bank. Any movement of funds must occur through the applicable authorized flow and after identity, sanctions, fraud, payment, corridor and provider controls are satisfied.'}</p></section>
  </main>;
}
