import {supabaseServer} from '@/lib/supabase/server';
export const dynamic='force-dynamic';
export const runtime='nodejs';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function json(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
function text(v:unknown,max:number){const s=String(v??'').trim();return s?s.slice(0,max):null}
function num(v:unknown){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:NaN}
async function ctx(){const supabase=await supabaseServer();const {data:{user}}=await supabase.auth.getUser();return {supabase,user}}
export async function GET(){const {supabase,user}=await ctx();if(!user)return json({error:'UNAUTHORIZED'},401);const [{data:provider},{data:businesses},{data:items,error}]=await Promise.all([supabase.from('delivery_provider_profiles').select('user_id,business_id,display_name,profile_status').eq('user_id',user.id).maybeSingle(),supabase.from('businesses').select('id,legal_name,trade_name,country_code,kyb_status').eq('owner_user_id',user.id),supabase.from('provider_catalog_items').select('*').eq('provider_user_id',user.id).order('updated_at',{ascending:false})]);if(error)return json({error:'CATALOG_READ_FAILED'},500);return json({provider,businesses:businesses??[],items:items??[]})}
export async function POST(request:Request){const {supabase,user}=await ctx();if(!user)return json({error:'UNAUTHORIZED'},401);let b:Record<string,unknown>;try{b=await request.json()}catch{return json({error:'INVALID_JSON'},400)}const businessId=String(b.businessId??'');const itemType=String(b.itemType??'').toUpperCase();const title=String(b.title??'').trim();const category=String(b.category??'').trim();const currency=String(b.currency??'USD').trim().toUpperCase();const price=num(b.price),stock=num(b.stockQuantity);if(!UUID.test(businessId)||!['PRODUCT','SERVICE'].includes(itemType)||title.length<3||title.length>180||category.length<2||category.length>120||!/^[A-Z]{3}$/.test(currency)||Number.isNaN(price)||Number.isNaN(stock))return json({error:'INVALID_CATALOG_ITEM'},400);const {data:owned}=await supabase.from('businesses').select('id').eq('id',businessId).eq('owner_user_id',user.id).maybeSingle();const {data:provider}=await supabase.from('delivery_provider_profiles').select('user_id').eq('user_id',user.id).maybeSingle();if(!owned||!provider)return json({error:'PROVIDER_BUSINESS_REQUIRED'},403);const {data,error}=await supabase.from('provider_catalog_items').insert({provider_user_id:user.id,business_id:businessId,item_type:itemType,title,description:text(b.description,2000),category,currency,price,unit:text(b.unit,40),available:b.available!==false,stock_quantity:stock,service_area:text(b.serviceArea,240),image_url:text(b.imageUrl,500),conditions:text(b.conditions,1000),review_status:'PENDING'}).select('*').single();if(error)return json({error:'CATALOG_CREATE_FAILED'},400);return json({item:data,publication:'PENDING_REVIEW'},201)}
export async function PATCH(request:Request){const {supabase,user}=await ctx();if(!user)return json({error:'UNAUTHORIZED'},401);let b:Record<string,unknown>;try{b=await request.json()}catch{return json({error:'INVALID_JSON'},400)}const id=String(b.id??'');if(!UUID.test(id))return json({error:'INVALID_ITEM_ID'},400);const price=num(b.price),stock=num(b.stockQuantity);if(Number.isNaN(price)||Number.isNaN(stock))return json({error:'INVALID_PRICE_OR_STOCK'},400);const patch:any={updated_at:new Date().toISOString(),review_status:'PENDING'};const fields:Array<[string,string|null]>=[['title',text(b.title,180)],['description',text(b.description,2000)],['category',text(b.category,120)],['unit',text(b.unit,40)],['service_area',text(b.serviceArea,240)],['image_url',text(b.imageUrl,500)],['conditions',text(b.conditions,1000)]];for(const [k,v] of fields)if(v!==null)patch[k]=v;if(b.currency)patch.currency=String(b.currency).toUpperCase();if(b.price!==undefined)patch.price=price;if(b.stockQuantity!==undefined)patch.stock_quantity=stock;if(b.available!==undefined)patch.available=Boolean(b.available);const {data,error}=await supabase.from('provider_catalog_items').update(patch).eq('id',id).eq('provider_user_id',user.id).select('*').single();if(error)return json({error:'CATALOG_UPDATE_FAILED'},400);return json({item:data,publication:'PENDING_REVIEW'})}
export async function DELETE(request:Request){const {supabase,user}=await ctx();if(!user)return json({error:'UNAUTHORIZED'},401);let b:any;try{b=await request.json()}catch{return json({error:'INVALID_JSON'},400)}const id=String(b.id??'');if(!UUID.test(id))return json({error:'INVALID_ITEM_ID'},400);const {error}=await supabase.from('provider_catalog_items').delete().eq('id',id).eq('provider_user_id',user.id);if(error)return json({error:'CATALOG_DELETE_FAILED'},400);return json({deleted:true})}
