'use client';

import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {localeOf} from '@/lib/i18n';

type Item={provider_user_id:string;service_code:string;active:boolean;fee_currency:string;starting_fee:number|null;minimum_fee:number|null;maximum_fee:number|null;eta_min_minutes:number|null;eta_max_minutes:number|null;conditions:string|null;approval_status:string;updated_at:string;provider?:{public_provider_id:string|null;display_name:string;profile_status:string;country_code:string|null;city:string|null}|null};

export default function ProviderServiceReview(){
  const params=useParams<{locale:string}>();const locale=localeOf(params?.locale);const es=locale==='es';
  const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
  async function load(){const res=await fetch('/api/provider-services/review',{cache:'no-store'});const body=await res.json().catch(()=>({}));if(res.status===401){window.location.href=`/${locale}/auth`;return;}if(res.ok)setItems(body.items??[]);else setMessage(body.error??'Unable to load review queue.');setLoading(false);}
  useEffect(()=>{load()},[]);
  async function decide(item:Item,decision:'APPROVED'|'REJECTED'|'SUSPENDED'){const key=`${item.provider_user_id}:${item.service_code}`;setBusy(key);setMessage('');const res=await fetch('/api/provider-services/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerUserId:item.provider_user_id,serviceCode:item.service_code,decision})});const body=await res.json().catch(()=>({}));if(res.ok){setMessage(es?`Decisión guardada: ${decision}.`:`Decision saved: ${decision}.`);await load();}else setMessage(body.error??'Review update failed.');setBusy('');}
  return <main className="shell premiumAppShell"><nav className="nav premiumNav"><a href={`/${locale}`} className="brandwrap"><div className="brand">mycubacash</div><small>{es?'Command Center':'Command Center'}</small></a><div className="navlinks"><a href={`/${locale}/dashboard`}>Dashboard</a><a href={`/${locale}/local-services`}>{es?'Servicios locales':'Local services'}</a></div></nav>
  <section className="section" style={{maxWidth:1100,margin:'0 auto'}}><div className="sectionHead"><div><span className="eyebrow">{es?'REVISIÓN DE SERVICIOS':'SERVICE REVIEW'}</span><h2>{es?'Aprueba solo servicios verificables y seguros':'Approve only verifiable, safe services'}</h2></div><p>{es?'La aprobación publica el servicio solo cuando el proveedor también está verificado. Rechaza o suspende cualquier oferta ambigua, no verificable o que intente presentar actividad financiera regulada como un servicio local.':'Approval publishes the service only when the provider is also verified. Reject or suspend ambiguous, unverifiable offers or attempts to disguise regulated financial activity as a local service.'}</p></div>
  {loading?<p>{es?'Cargando…':'Loading…'}</p>:!items.length?<div className="feature premiumCard"><h3>{es?'Cola limpia':'Queue clear'}</h3><p>{es?'No hay servicios pendientes de revisión.':'No provider services are pending review.'}</p></div>:<div className="featureGrid">{items.map(item=>{const key=`${item.provider_user_id}:${item.service_code}`;return <article className="feature premiumCard" key={key}><span className="eyebrow">{item.service_code}</span><h3>{item.provider?.display_name??'Provider'}</h3><p><strong>ID:</strong> {item.provider?.public_provider_id??'—'}</p><p><strong>{es?'Ubicación':'Location'}:</strong> {[item.provider?.city,item.provider?.country_code].filter(Boolean).join(' · ')||'—'}</p><p><strong>{es?'Estado proveedor':'Provider status'}:</strong> {item.provider?.profile_status??'—'}</p><p><strong>{es?'Oferta activa':'Offer active'}:</strong> {item.active?'YES':'NO'} · <strong>{es?'Revisión':'Review'}:</strong> {item.approval_status}</p>{item.starting_fee!=null&&<p><strong>{es?'Desde':'From'}:</strong> {Number(item.starting_fee).toFixed(2)} {item.fee_currency}</p>}{(item.eta_min_minutes!=null||item.eta_max_minutes!=null)&&<p><strong>ETA:</strong> {item.eta_min_minutes??'—'}–{item.eta_max_minutes??'—'} min</p>}{item.conditions&&<p>{item.conditions}</p>}<div className="actions"><button className="cta premiumCta" disabled={busy===key} onClick={()=>decide(item,'APPROVED')}>{es?'Aprobar':'Approve'}</button><button className="ghost" disabled={busy===key} onClick={()=>decide(item,'REJECTED')}>{es?'Rechazar':'Reject'}</button><button className="ghost" disabled={busy===key} onClick={()=>decide(item,'SUSPENDED')}>{es?'Suspender':'Suspend'}</button></div></article>})}</div>}
  {message&&<p role="status">{message}</p>}</section></main>;
}
